### ISSUE TITLE
how to select drawn polygon active on mouse down

### ISSUE THREAD

**Issue by RajasekharKadasani** [sedrakpc/angular-canvas-area-draw#4]
on mouse down select polygon not able to achieve

**Comment by sedrakpc** [comment]
For example if you have code like this:
```
<div canvas-area-draw points="points"
     active="activePolygon" image-url="imageSrc"
     enabled="enabled" palette="colorArray"></div>
```
**activePolygon** variable monitors active polygon index inside **points** array. Changing it you will change active polygon and you can bind it to any event you want.
